[server]
addr = "127.0.0.1"
port = 7878

[[period]]
name = "最近一年"
start = "2025-01-01"
end = "2025-12-31"

[[period]]
name = "最近三年"
start = "2023-01-01"
end = "2025-12-31"

[[period]]
name = "最近五年"
start = "2021-01-01"
end = "2025-12-31"

[[period]]
name = "最近十年"
start = "2016-01-01"
end = "2025-12-31"

[[period]]
name = "迅投同期"
start = "2023-10-10"
end = "2024-09-30"

[data]
market = "data/market"
metadata = "data/metadata.json"
